#!/bin/sh


# Discover all the Matlab Installations
installation_directories=$(ls /usr/local/matlab/ | grep 'R')
tLen=${#installation_directories[@]}

# Pick the last one
last_installation=${installation_directories[$tLen-1]}

# Where am I?
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Command to execute
/usr/local/matlab/$last_installation/bin/matlab -nodesktop -nosplash -r "cd('$DIR/src/');EpiTools;"

