function [ProjIm,DepthMap] = createProjection(ImStack, SmoothingRadius, depthThreshold,SurfSmoothness1,SurfSmoothness2,ShowProcess)
% IN: takes in an image stack as generated by 'LoadImages'
% OUT: return a clean projection image

fprintf('Creating smart projection ... ')
tic

s=size(ImStack); 

% doing some simple smoothing
gaussianProfile = fspecial( 'gaussian', [s(1) s(2)], SmoothingRadius);
I1 = zeros([s(1), s(2),s(3) ]);
for z=1:s(3),
    I1(:,:,z) = real(fftshift(ifft2(fft2(ImStack(:,:,z)).*fft2(gaussianProfile))));
end

% ---- prepare surface ---------
[vm1,depthmap] = max(I1,[],3);
confidencemap = s(3)*vm1./sum(I1,3);

c = confidencemap(:);
confthres = median(c(c > median(c)));

% keep only the brightest surface points (intensity in 1 quartile) -
% assumed to be the surface of interest
depthmap2=depthmap.*double(confidencemap>confthres);

%now fit a surface through these high-intensity points

[y,x]=find( depthmap2 > 0);
z=depthmap2(depthmap2 > 0);

xnodes = 1:s(2);
ynodes = 1:s(1);
tilesize = max(s(1),s(2));
[zg1,xg1,yg1] = gridfit(x,y,z,xnodes,ynodes,'tilesize',tilesize,'overlap',0.25,'smoothness',SurfSmoothness1,'interp','bilinear','regularizer','springs');

if ShowProcess
    figure
    surf(xg1,yg1,zg1)
    shading interp
    colormap(jet(256))
    camlight right
    lighting phong
    title 'Tiled gridfit'
end


depthmap3=abs(zg1-depthmap2);

depthmap3(depthmap2==0)=0;
depthmap4 = depthmap2.*(depthmap3 < depthThreshold); % only keep points which are relatively close to our first estimate

% --- 2nd iteration

[y,x]=find( depthmap4 > 0);
z=depthmap4(depthmap4 > 0);


xnodes = 1:s(2);
ynodes = 1:s(1);
[zg2,xg2,yg2] = gridfit(x,y,z,xnodes,ynodes,'tilesize',tilesize,'overlap',0.25,'smoothness',SurfSmoothness2,'interp','bilinear','regularizer','springs');

if ShowProcess
    figure
    surf(xg2,yg2,zg2)
    shading interp
    colormap(jet(256))
    camlight right
    lighting phong
    title 'Tiled gridfit'
end

% ----- creating surface map from interpolated surface estimation ------

surface2=zeros(s(1),s(2),'uint16');

for y=1:s(1),
    for x=1:s(2),
           if (zg2(y,x) > 0)
             surface2(y,x)=ImStack(y,x,round(zg2(y,x)));
            end
    end
end

fprintf('Finished. ')
toc

ProjIm = surface2;
DepthMap = zg2;



